name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  java-cli:


    steps:

      - name: calling reusable-workflow
        uses: ./.github/workflows/reusable-java-ci.yml 
