name: Reusable Java CI

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name:
        run: mvn clean test package
